# Generated by Django 6.0.2 on 2026-02-04 01:15

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(default='시도/군구로 검색하고, 특성화고·마이스터고를 한 번에 확인하세요.', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='우리동네 직업계고 찾기', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='notice',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
