# Generated by Django 6.0.2 on 2026-02-04 01:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('school_type', models.CharField(max_length=50)),
                ('establishment', models.CharField(blank=True, default='', max_length=50)),
                ('education_office', models.CharField(blank=True, default='', max_length=100)),
                ('homepage', models.CharField(blank=True, default='', max_length=300)),
                ('zipcode', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('address_detail', models.CharField(blank=True, default='', max_length=300)),
                ('sido', models.CharField(max_length=30)),
                ('sigungu', models.CharField(max_length=30)),
                ('sublocal', models.CharField(blank=True, default='', max_length=60)),
                ('departments', models.TextField(blank=True, default='')),
                ('track_auto', models.CharField(blank=True, default='', max_length=50)),
                ('school_code', models.CharField(max_length=30, unique=True)),
                ('phone_principal', models.CharField(blank=True, default='', max_length=50)),
                ('phone_academic', models.CharField(blank=True, default='', max_length=50)),
                ('phone_admin', models.CharField(blank=True, default='', max_length=50)),
                ('phone_career', models.CharField(blank=True, default='', max_length=50)),
                ('fax', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['sido', 'sigungu', 'name'],
                'indexes': [models.Index(fields=['sido', 'sigungu', 'school_type'], name='schools_sch_sido_d2e28a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('ORIENTATION', '입학설명회'), ('CAMP', '신입생 캠프')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('location_or_link', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='schools.school')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
    ]
